export const SUBMIT_URL = 'SUBMIT_URL';
export const SUBMIT_URL_SUCCESS = 'SUBMIT_URL_SUCCESS';
export const SUBMIT_URL_FAIL = 'SUBMIT_URL_FAIL';
export const SUBMIT_DUPLICATE_URL = 'SUBMIT_DUPLICATE_URL';
export const UPDATE_URL = 'UPDATE_URL';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SORT_PRODUCT = 'SORT_PRODUCT';